version: "3.8"

services:
  frontend:
    build:
      context: .
      target: builder
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules
            - dist
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules # to preserve container dependencies
